### ISSUE TITLE
The application failed to start

### ISSUE THREAD

**Issue by divineniiquaye** [leafsphp/leafMVC#12]
# Description

I git cloned this repository, run composer update, and typed `php leaf serve` in the terminal and it failed. I then decided to use `php -S 127.0.0.1:8000 index.php`, it failed again. Here are screenshots of the error which occurred.

Upon viewing the application from the web:
![image](https://user-images.githubusercontent.com/53147395/142824614-090f528d-a1e6-4652-a664-5f46f9568142.png)

This was the error emitted on the terminal:
![image](https://user-images.githubusercontent.com/53147395/142825309-98f4d159-ef2a-4d20-8a24-f95833e94eb5.png)

# Motivation and context

I came across this project on GitHub and upon reading the documentation at https://leafphp.dev, I decided to give it a try. I expected better than what was advertised.

Just to note, my PHP version is 8.0.12 and my PC is Linux, Additionally, the error that occurred while running the application has nothing to do with the PHP version, or nor the machine I use.

# Expected Behavior or Solution

I see the leaf framework has numerous bugs which needs to be fixed. Every time I try to fix something, I'm confronted with another bug. I can't recommend a clear solution, as the project is too buggy.

**Comment by mychidarko** [comment]
> I came across this project on GitHub and upon reading the documentation at https://leafphp.dev, I decided to give it a try. I expected better than what was advertised.

Leaf PHP is actually better than this. You appear to be using the Leaf MVC 3 preview, which as mentioned is still unstable and is being worked on at the moment. Restructuring the directories and splitting leaf apart are all changes coming up in v3 and have not yet been proven to work on all systems.

> Just to note, my PHP version is 8.0.12 and my PC is Linux, Additionally, the error that occurred while running the application has nothing to do with the PHP version, or nor the machine I use.

Of course, this has nothing to do with your system. However, I would recommend that you use Leaf MVC 2. You can find the documentation at [https://archive.leafphp.dev](https://archive.leafphp.dev/#/leaf-mvc/) while these bugs you pointed out are resolved. Thanks once again

**Comment by mychidarko** [comment]
Everything pointed out has been fixed successfully. Most of it was caused by references to the earlier upper cased folder names although there were still some other bugs. A mistake on my part for assuming Mac was case-sensitive like Linux is. A new preview version will be released soon which has all the fixes, however, you can install the 3.x branch and you should be fine.

I'll like to apologise again to you @divineniiquaye and all other linux users who may have encountered these problems, and also thank you for pointing them out.

**Comment by divineniiquaye** [comment]
Hello @mychidarko, unfortunately, the error still exists. I see you fixed the blade template file not found issue. The `leafs/mvc-core` uses `^1.1` instead of `dev-main` in the composer.json file. No problem, this is a minor change as there will be a new release you earlier stated.

The application security in terms of folder structure isn't the best. The **index.php** file outside of the **public** folder should be able to move around and get served from the browser.

Let's break this down:

1. Application unable to start, changing the version of the `leafs/mvc-core` to **dev-main** in the composer.json file and running `composer update` fixes that.

2. After the change, the application runs as expected when running from a web server, using the `php leaf serve` command or `php -S 127.0.0.1:8000`. To test if the application can run anywhere, I used the command `php -S 127.0.0.1:8000 index.php`. And it failed to find the CSS file. Here is a screenshot below.

![image](https://user-images.githubusercontent.com/53147395/143000194-78ba5e33-12d6-43a0-b3f4-5180d060dc47.png)

With the image above, you can see the un-safe URL linking the CSS file. I navigated to the CSS file on the browser, and here is a screenshot of the outcome.

![image](https://user-images.githubusercontent.com/53147395/143001033-8770c9a3-6dad-4434-b3c3-125794a1fd90.png)

I copied the assets folder into the base folder where the **index.php** file lives and added a few changes to the `index.blade.php` file on line 9.

```diff
-     <link rel="stylesheet" href="{{ ViewsPath('assets/css/styles.css') }}">
+     <link rel="stylesheet" href="/assets/css/styles.css">
```

Oops, encountered error 404 again. So here is my suggested change which is borrowed from [Laminas MVC Skeleton](https://github.com/laminas/laminas-mvc-skeleton):

```php
// see https://github.com/laminas/laminas-mvc-skeleton/blob/1.3.x/public/index.php#L14-L21
// Decline static file requests back to the PHP built-in webserver
if (PHP_SAPI === 'cli-server') {
    $path = realpath(__DIR__ . parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH));
    if (is_string($path) && __FILE__ !== $path && is_file($path)) {
        return false;
    }
    unset($path);
}
```

Finally, to note, with this setting, this application can be deployed anywhere including gcloud. However, using the suggested change in the index file outside the **public** folder in a production environment has security issues. Which is why I suggest changing the folder structure of this application.

**Comment by mychidarko** [comment]
🥲 I'll give this a thorough look

**Comment by mychidarko** [comment]
Hi @divineniiquaye. All the issues you pointed out have been fixed. In terms of the `index.php`, I decided to make use of the `public` directory just as you suggested. However, you might notice there's still an `index.php` file in the root directory. That links to the index in the public directory for use in development and on shared hosts which don't fully support the public root .

In terms of assets, static assets are now kept in the `public` directory as is done in other frameworks. You can access these with `PublicPath`. The documentation for this will be updated soon. For now though, I would need you to confirm if these changes work as intended. Thanks
